export const cardsData = [
  {
    name: "ابراهيم حسن",
    image: "https://images.unsplash.com/photo-1463453091185-61582044d556?auto=format&fit=facearea&w=400&h=400&facepad=2&q=80",
    rank: "امين المجتمع",
    email: "circum:mail",
    phone: "ph:phone-call-thin",
    send: "gm@nmbd.org",
    dail: "0917150001",
  },
  {
    name: "نادية محمد",
    image: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=facearea&w=400&h=400&facepad=2&q=80",
    rank: "عضو الامانة",
    email: "circum:mail",
    phone: "ph:phone-call-thin",
    send: "hm@nmbd.org",
    dail: "0917150001",
  },
  // {
  //   name: "المقداد الهجان",
  //   image: "/author/1.jpg",
  //   rank: "الامين الثقافي",
  //   email: "circum:mail",
  //   phone: "ph:phone-call-thin",
  //   send: "gm@nmbd.org",
  //   dail: "0917150001",
  // },
  // {
  //   name: "زهير طه",
  //   image: "/author/2.jpg",
  //   rank: "الامين الاعلامي",
  //   email: "circum:mail",
  //   phone: "ph:phone-call-thin",
  //   send: "gm@nmbd.org",
  //   dail: "0917150001",
  // },
];
